name: Run ServeRest Tests

on:
  schedule:
    - cron: '0 20 * * *'

  push:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        node-version: [ 22.x ] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        browser: [ chrome, firefox ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress Tests
        run: |
          npx cypress run \
            --record \
            --key eec2f54c-de1d-4cdf-9efa-bcf45a7fc51c \
            --parallel \
            --group "browser-${{ matrix.browser }}" \
            --browser ${{ matrix.browser }} 

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results
