name: Run ServeRest Tests

on:
  schedule:
    - cron: '0 20 * * *'

  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        node-version: [ 22.x ] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        browser: [ chrome, firefox ]
        containers: [1, 2] # Uses 2 parallel instances

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress Tests
        run: |
          npx cypress run \

            --browser ${{ matrix.browser }} 

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results
