name: Run ServeRest Tests

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ main ]

jobs:
  chrome-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Install Cypress
        run: npx cypress install
      - name: Run Chrome Tests
        run: |
          npx cypress run \
            --record \
            --key eec2f54c-de1d-4cdf-9efa-bcf45a7fc51c \
            --browser chrome
      - name: Upload Chrome results
        uses: actions/upload-artifact@v4
        with:
          name: chrome-results
          path: test-results

  firefox-tests:
    needs: chrome-tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm i
      - name: Install Cypress
        run: npx cypress install
      - name: Run Firefox Tests
        run: |
          npx cypress run \
            --record \
            --key eec2f54c-de1d-4cdf-9efa-bcf45a7fc51c \
            --browser firefox
      - name: Upload Firefox results
        uses: actions/upload-artifact@v4
        with:
          name: firefox-results
          path: test-results
